
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
    return knex('car_makes').del()
        .then(function () {
      // Inserts seed entries
            return knex('car_makes').insert([
                { id: 1, name: 'Abarth', show: true },
                { id: 2, name: 'AC', show: true },
                { id: 3, name: 'Acura', show: true },
                { id: 4, name: 'Alfa Romeo', show: true },
                { id: 5, name: 'Allard', show: true },
                { id: 6, name: 'Alpina', show: true },
                { id: 7, name: 'Alpine', show: true },
                { id: 8, name: 'Alvis', show: true },
                { id: 9, name: 'AMC', show: true },
                { id: 10, name: 'Ariel', show: true },
                { id: 11, name: 'Armstrong Siddeley', show: true },
                { id: 12, name: 'Ascari', show: true },
                { id: 13, name: 'Aston Martin', show: true },
                { id: 14, name: 'Audi', show: true },
                { id: 15, name: 'Austin', show: true },
                { id: 16, name: 'Austin-Healey', show: true },
                { id: 17, name: 'Autobianchi', show: true },
                { id: 18, name: 'Auverland', show: true },
                { id: 19, name: 'Avanti', show: true },
                { id: 20, name: 'Beijing', show: true },
                { id: 21, name: 'Bentley', show: true },
                { id: 22, name: 'Berkeley', show: true },
                { id: 23, name: 'Bitter', show: true },
                { id: 24, name: 'Bizzarrini', show: true },
                { id: 25, name: 'BMW', show: true },
                { id: 26, name: 'Brilliance', show: true },
                { id: 27, name: 'Bristol', show: true },
                { id: 28, name: 'Bugatti', show: true },
                { id: 29, name: 'Buick', show: true },
                { id: 30, name: 'Cadillac', show: true },
                { id: 31, name: 'Caterham', show: true },
                { id: 32, name: 'Checker', show: true },
                { id: 33, name: 'Chevrolet', show: true },
                { id: 34, name: 'Chrysler', show: true },
                { id: 35, name: 'Citroen', show: true },
                { id: 36, name: 'Dacia', show: true },
                { id: 37, name: 'Daewoo', show: true },
                { id: 38, name: 'DAF', show: true },
                { id: 39, name: 'Daihatsu', show: true },
                { id: 40, name: 'Daimler', show: true },
                { id: 41, name: 'Datsun', show: true },
                { id: 42, name: 'De Tomaso', show: true },
                { id: 43, name: 'DKW', show: true },
                { id: 44, name: 'Dodge', show: true },
                { id: 45, name: 'Donkervoort', show: true },
                { id: 46, name: 'Eagle', show: true },
                { id: 47, name: 'Fairthorpe', show: true },
                { id: 48, name: 'Ferrari', show: true },
                { id: 49, name: 'Fiat', show: true },
                { id: 50, name: 'Fisker', show: true },
                { id: 51, name: 'Ford', show: true },
                { id: 52, name: 'GAZ', show: true },
                { id: 53, name: 'Geely', show: true },
                { id: 54, name: 'Ginetta', show: true },
                { id: 55, name: 'GMC', show: true },
                { id: 56, name: 'Holden', show: true },
                { id: 57, name: 'Honda', show: true },
                { id: 58, name: 'Hudson', show: true },
                { id: 59, name: 'Humber', show: true },
                { id: 60, name: 'Hummer', show: true },
                { id: 61, name: 'Hyundai', show: true },
                { id: 62, name: 'Infiniti', show: true },
                { id: 63, name: 'Innocenti', show: true },
                { id: 64, name: 'Isuzu', show: true },
                { id: 65, name: 'Italdesign', show: true },
                { id: 66, name: 'Jaguar', show: true },
                { id: 67, name: 'Jeep', show: true },
                { id: 68, name: 'Jensen', show: true },
                { id: 69, name: 'Kia', show: true },
                { id: 70, name: 'Koenigsegg', show: true },
                { id: 71, name: 'Lada', show: true },
                { id: 72, name: 'Lamborghini', show: true },
                { id: 73, name: 'Lancia', show: true },
                { id: 74, name: 'Land Rover', show: true },
                { id: 75, name: 'Lexus', show: true },
                { id: 76, name: 'Lincoln', show: true },
                { id: 77, name: 'Lotec', show: true },
                { id: 78, name: 'Lotus', show: true },
                { id: 79, name: 'Luxgen', show: true },
                { id: 80, name: 'Mahindra', show: true },
                { id: 81, name: 'Marcos', show: true },
                { id: 82, name: 'Maserati', show: true },
                { id: 83, name: 'Matra-Simca', show: true },
                { id: 84, name: 'Maybach', show: true },
                { id: 85, name: 'Mazda', show: true },
                { id: 86, name: 'MCC', show: true },
                { id: 87, name: 'McLaren', show: true },
                { id: 88, name: 'Mercedes-Benz', show: true },
                { id: 89, name: 'Mercury', show: true },
                { id: 90, name: 'MG', show: true },
                { id: 91, name: 'Mini', show: true },
                { id: 92, name: 'Mitsubishi', show: true },
                { id: 93, name: 'Monteverdi', show: true },
                { id: 94, name: 'Moretti', show: true },
                { id: 95, name: 'Morgan', show: true },
                { id: 96, name: 'Morris', show: true },
                { id: 97, name: 'Nissan', show: true },
                { id: 98, name: 'Noble', show: true },
                { id: 99, name: 'NSU', show: true },
                { id: 100, name: 'Oldsmobile', show: true },
                { id: 101, name: 'Opel', show: true },
                { id: 102, name: 'Packard', show: true },
                { id: 103, name: 'Pagani', show: true },
                { id: 104, name: 'Panoz', show: true },
                { id: 105, name: 'Peugeot', show: true },
                { id: 106, name: 'Pininfarina', show: true },
                { id: 107, name: 'Plymouth', show: true },
                { id: 108, name: 'Pontiac', show: true },
                { id: 109, name: 'Porsche', show: true },
                { id: 110, name: 'Proton', show: true },
                { id: 111, name: 'Reliant', show: true },
                { id: 112, name: 'Renault', show: true },
                { id: 113, name: 'Riley', show: true },
                { id: 114, name: 'Rolls-Royce', show: true },
                { id: 115, name: 'Rover', show: true },
                { id: 116, name: 'Saab', show: true },
                { id: 117, name: 'Saleen', show: true },
                { id: 118, name: 'Samsung', show: true },
                { id: 119, name: 'Saturn', show: true },
                { id: 120, name: 'Scion', show: true },
                { id: 121, name: 'Seat', show: true },
                { id: 122, name: 'Simca', show: true },
                { id: 123, name: 'Singer', show: true },
                { id: 124, name: 'Skoda', show: true },
                { id: 125, name: 'Smart', show: true },
                { id: 126, name: 'Spyker', show: true },
                { id: 127, name: 'SsangYong', show: true },
                { id: 128, name: 'SSC', show: true },
                { id: 129, name: 'Steyr', show: true },
                { id: 130, name: 'Studebaker', show: true },
                { id: 131, name: 'Subaru', show: true },
                { id: 132, name: 'Sunbeam', show: true },
                { id: 133, name: 'Suzuki', show: true },
                { id: 134, name: 'Talbot', show: true },
                { id: 135, name: 'Tata', show: true },
                { id: 136, name: 'Tatra', show: true },
                { id: 137, name: 'Tesla', show: true },
                { id: 138, name: 'Toyota', show: true },
                { id: 139, name: 'Trabant', show: true },
                { id: 140, name: 'Triumph', show: true },
                { id: 141, name: 'TVR', show: true },
                { id: 142, name: 'Vauxhall', show: true },
                { id: 143, name: 'Vector', show: true },
                { id: 144, name: 'Venturi', show: true },
                { id: 145, name: 'Volkswagen', show: true },
                { id: 146, name: 'Volvo', show: true },
                { id: 147, name: 'Wartburg', show: true },
                { id: 148, name: 'Westfield', show: true },
                { id: 149, name: 'Willys-Overland', show: true },
                { id: 150, name: 'Xedos', show: true },
                { id: 151, name: 'Zagato', show: true },
                { id: 152, name: 'Zastava', show: true },
                { id: 153, name: 'ZAZ', show: true },
                { id: 154, name: 'Zenvo', show: true },
                { id: 155, name: 'ZIL', show: true }
            ])
        })
        .then(() => {
            knex.raw(`SELECT setval('car_makes_id_seq', (SELECT MAX(id) FROM car_makes));`)
        })
}
