let hipIp = require('hipsteripsum')
let { transportTypeArr: transTypes, postTypeArr: postTypes } = require('../lists.js')
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('posts').del()
    .then(function () {
      // Inserts seed entries
      return knex('posts').insert([
        { id: 1, title: hipIp.getWords(Math.floor(Math.random() * 6) + 1) + ' ONE', content: hipIp.getWords(Math.floor(Math.random() * 100) + 1) + ' ONE', self_transportation_index: Math.floor(Math.random() * transTypes.length), self_car_make_id: Math.floor(Math.random() * 155) + 1, self_car_model: hipIp.getWords(1), self_car_year: `${Math.floor(Math.random() * 118) + 1901}`, self_car_color: hipIp.getWords(Math.floor(Math.random() * 2) + 1), other_transportation_index: Math.floor(Math.random() * transTypes.length), other_car_make_id: Math.floor(Math.random() * 155) + 1, other_car_model: hipIp.getWords(1), other_car_color: hipIp.getWords(Math.floor(Math.random() * 2) + 1), post_type_index: Math.floor(Math.random() * postTypes.length)},
        { id: 2, title: hipIp.getWords(Math.floor(Math.random() * 6) + 1) + ' TWO', content: hipIp.getWords(Math.floor(Math.random() * 100) + 1) + ' TWO', self_transportation_index: Math.floor(Math.random() * transTypes.length), self_car_make_id: Math.floor(Math.random() * 155) + 1, self_car_model: hipIp.getWords(1), self_car_year: `${Math.floor(Math.random() * 118) + 1901}`, self_car_color: hipIp.getWords(Math.floor(Math.random() * 2) + 1), other_transportation_index: Math.floor(Math.random() * transTypes.length), other_car_make_id: Math.floor(Math.random() * 155) + 1, other_car_model: hipIp.getWords(1), other_car_color: hipIp.getWords(Math.floor(Math.random() * 2) + 1), post_type_index: Math.floor(Math.random() * postTypes.length) },
        { id: 3, title: hipIp.getWords(Math.floor(Math.random() * 6) + 1) + ' THREE', content: hipIp.getWords(Math.floor(Math.random() * 100) + 1) + ' THREE', self_transportation_index: Math.floor(Math.random() * transTypes.length), self_car_make_id: Math.floor(Math.random() * 155) + 1, self_car_model: hipIp.getWords(1), self_car_year: `${Math.floor(Math.random() * 118) + 1901}`, self_car_color: hipIp.getWords(Math.floor(Math.random() * 2) + 1), other_transportation_index: Math.floor(Math.random() * transTypes.length), other_car_make_id: Math.floor(Math.random() * 155) + 1, other_car_model: hipIp.getWords(1), other_car_color: hipIp.getWords(Math.floor(Math.random() * 2) + 1), post_type_index: Math.floor(Math.random() * postTypes.length) },
        { id: 4, title: hipIp.getWords(Math.floor(Math.random() * 6) + 1) + ' FOUR', content: hipIp.getWords(Math.floor(Math.random() * 100) + 1) + ' FOUR', self_transportation_index: Math.floor(Math.random() * transTypes.length), self_car_make_id: Math.floor(Math.random() * 155) + 1, self_car_model: hipIp.getWords(1), self_car_year: `${Math.floor(Math.random() * 118) + 1901}`, self_car_color: hipIp.getWords(Math.floor(Math.random() * 2) + 1), other_transportation_index: Math.floor(Math.random() * transTypes.length), other_car_make_id: Math.floor(Math.random() * 155) + 1, other_car_model: hipIp.getWords(1), other_car_color: hipIp.getWords(Math.floor(Math.random() * 2) + 1), post_type_index: Math.floor(Math.random() * postTypes.length) },
        { id: 5, title: hipIp.getWords(Math.floor(Math.random() * 6) + 1) + ' FIVE', content: hipIp.getWords(Math.floor(Math.random() * 100) + 1) + ' FIVE', self_transportation_index: Math.floor(Math.random() * transTypes.length), self_car_make_id: Math.floor(Math.random() * 155) + 1, self_car_model: hipIp.getWords(1), self_car_year: `${Math.floor(Math.random() * 118) + 1901}`, self_car_color: hipIp.getWords(Math.floor(Math.random() * 2) + 1), other_transportation_index: Math.floor(Math.random() * transTypes.length), other_car_make_id: Math.floor(Math.random() * 155) + 1, other_car_model: hipIp.getWords(1), other_car_color: hipIp.getWords(Math.floor(Math.random() * 2) + 1), post_type_index: Math.floor(Math.random() * postTypes.length) },
        { id: 6, title: hipIp.getWords(Math.floor(Math.random() * 6) + 1) + ' SIX', content: hipIp.getWords(Math.floor(Math.random() * 100) + 1) + ' SIX', self_transportation_index: Math.floor(Math.random() * transTypes.length), self_car_make_id: Math.floor(Math.random() * 155) + 1, self_car_model: hipIp.getWords(1), self_car_year: `${Math.floor(Math.random() * 118) + 1901}`, self_car_color: hipIp.getWords(Math.floor(Math.random() * 2) + 1), other_transportation_index: Math.floor(Math.random() * transTypes.length), other_car_make_id: Math.floor(Math.random() * 155) + 1, other_car_model: hipIp.getWords(1), other_car_color: hipIp.getWords(Math.floor(Math.random() * 2) + 1), post_type_index: Math.floor(Math.random() * postTypes.length) },
        { id: 7, title: hipIp.getWords(Math.floor(Math.random() * 6) + 1) + ' SEVEN', content: hipIp.getWords(Math.floor(Math.random() * 100) + 1) + ' SEVEN', self_transportation_index: Math.floor(Math.random() * transTypes.length), self_car_make_id: Math.floor(Math.random() * 155) + 1, self_car_model: hipIp.getWords(1), self_car_year: `${Math.floor(Math.random() * 118) + 1901}`, self_car_color: hipIp.getWords(Math.floor(Math.random() * 2) + 1), other_transportation_index: Math.floor(Math.random() * transTypes.length), other_car_make_id: Math.floor(Math.random() * 155) + 1, other_car_model: hipIp.getWords(1), other_car_color: hipIp.getWords(Math.floor(Math.random() * 2) + 1), post_type_index: Math.floor(Math.random() * postTypes.length) },
        { id: 8, title: hipIp.getWords(Math.floor(Math.random() * 6) + 1) + ' EIGHT', content: hipIp.getWords(Math.floor(Math.random() * 100) + 1) + ' EIGHT', self_transportation_index: Math.floor(Math.random() * transTypes.length), self_car_make_id: Math.floor(Math.random() * 155) + 1, self_car_model: hipIp.getWords(1), self_car_year: `${Math.floor(Math.random() * 118) + 1901}`, self_car_color: hipIp.getWords(Math.floor(Math.random() * 2) + 1), other_transportation_index: Math.floor(Math.random() * transTypes.length), other_car_make_id: Math.floor(Math.random() * 155) + 1, other_car_model: hipIp.getWords(1), other_car_color: hipIp.getWords(Math.floor(Math.random() * 2) + 1), post_type_index: Math.floor(Math.random() * postTypes.length) },
        { id: 9, title: hipIp.getWords(Math.floor(Math.random() * 6) + 1) + ' NINE', content: hipIp.getWords(Math.floor(Math.random() * 100) + 1) + ' NINE', self_transportation_index: Math.floor(Math.random() * transTypes.length), self_car_make_id: Math.floor(Math.random() * 155) + 1, self_car_model: hipIp.getWords(1), self_car_year: `${Math.floor(Math.random() * 118) + 1901}`, self_car_color: hipIp.getWords(Math.floor(Math.random() * 2) + 1), other_transportation_index: Math.floor(Math.random() * transTypes.length), other_car_make_id: Math.floor(Math.random() * 155) + 1, other_car_model: hipIp.getWords(1), other_car_color: hipIp.getWords(Math.floor(Math.random() * 2) + 1), post_type_index: Math.floor(Math.random() * postTypes.length) },
        { id: 10, title: hipIp.getWords(Math.floor(Math.random() * 6) + 1) + ' TEN', content: hipIp.getWords(Math.floor(Math.random() * 100) + 1) + ' TEN', self_transportation_index: Math.floor(Math.random() * transTypes.length), self_car_make_id: Math.floor(Math.random() * 155) + 1, self_car_model: hipIp.getWords(1), self_car_year: `${Math.floor(Math.random() * 118) + 1901}`, self_car_color: hipIp.getWords(Math.floor(Math.random() * 2) + 1), other_transportation_index: Math.floor(Math.random() * transTypes.length), other_car_make_id: Math.floor(Math.random() * 155) + 1, other_car_model: hipIp.getWords(1), other_car_color: hipIp.getWords(Math.floor(Math.random() * 2) + 1), post_type_index: Math.floor(Math.random() * postTypes.length) },
        { id: 11, title: hipIp.getWords(Math.floor(Math.random() * 6) + 1) + ' ELEVEN', content: hipIp.getWords(Math.floor(Math.random() * 100) + 1) + ' ELEVEN' , self_transportation_index: Math.floor(Math.random() * transTypes.length), self_car_make_id: Math.floor(Math.random() * 155) + 1, self_car_model: hipIp.getWords(1), self_car_year: `${Math.floor(Math.random() * 118) + 1901}`, self_car_color: hipIp.getWords(Math.floor(Math.random() * 2) + 1), other_transportation_index: Math.floor(Math.random() * transTypes.length), other_car_make_id: Math.floor(Math.random() * 155) + 1, other_car_model: hipIp.getWords(1), other_car_color: hipIp.getWords(Math.floor(Math.random() * 2) + 1), post_type_index: Math.floor(Math.random() * postTypes.length) },
        { id: 12, title: hipIp.getWords(Math.floor(Math.random() * 6) + 1) + ' TWELVE', content: hipIp.getWords(Math.floor(Math.random() * 100) + 1) + ' TWELVE', self_transportation_index: Math.floor(Math.random() * transTypes.length), self_car_make_id: Math.floor(Math.random() * 155) + 1, self_car_model: hipIp.getWords(1), self_car_year: `${Math.floor(Math.random() * 118) + 1901}`, self_car_color: hipIp.getWords(Math.floor(Math.random() * 2) + 1), other_transportation_index: Math.floor(Math.random() * transTypes.length), other_car_make_id: Math.floor(Math.random() * 155) + 1, other_car_model: hipIp.getWords(1), other_car_color: hipIp.getWords(Math.floor(Math.random() * 2) + 1), post_type_index: Math.floor(Math.random() * postTypes.length) }
      ])
    })
    .then(() => {
      knex.raw(`SELECT setval('posts_id_seq', (SELECT MAX(id) FROM posts));`)
    })
}
